proxy-providers:
 çº¢æäº‘:
    type: http
    interval: 21600
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: ğŸŸ¢ ç›´è¿
    url: "http://106.55.228.246:36666/hxvip?token=c3df3c5d3e8dcd8a540cd81614b56245"

 ä¸€å…ƒ:
    type: http
    interval: 10800
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: ğŸŸ¢ ç›´è¿
    url: "https://sub3.smallstrawberry.com/api/v1/client/subscribe?token=38b35f4e498ea68ea3b0e035143c9393"

proxies:
- name: "ğŸŸ¢ ç›´è¿"
  type: direct
  udp: true

mixed-port: 7890
ipv6: false
allow-lan: true
unified-delay: false
tcp-concurrent: true
external-controller: 127.0.0.1:9090
external-ui: ui
external-ui-url: "https://ghproxy.com/https://github.com/MetaCubeX/metacubexd/archive/gh-pages.zip"

find-process-mode: strict
global-client-fingerprint: chrome

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "+.push.apple.com"
    - "+.baidu.com"
    - "+.mi.com"
    - "+.alibaba.com"
    - "+.google-analytics.com"
    - "*.doubleclick.net"
    - "+.paypal.com"
    - "*.alipay.com"
    - "telegram.org"
    - "t.me"
  skip-ip-cidr:
    - 91.108.56.0/24       # Telegram
    - 149.154.160.0/20     # Telegram
    - 148.135.0.0/16       # Meta/Facebook
    - 157.240.0.0/16       # Facebook/Instagram
  force-domain:
    - "+.youtube.com"
    - "+.googlevideo.com"
    - "+.facebook.com"
    - "+.twitter.com"

tun:
  enable: true
  stack: mixed
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true

dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-filter:
    - "+.lan"
    - "+.local"
    - "+.home.arpa"
    - "+.localdomain"
    - "+.invalid"
    - geosite:cn
    - geosite:private
    - "+.market.xiaomi.com"
    - "connectivitycheck.gstatic.com"
    - "+.google.cn"
    - "+.googleapis.cn"
    - "+.gvt1.com"
    - "+.gtimg.com"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - "+.captive.apple.com"
    - "+.ntp.org"
    - "+.pool.ntp.org"
    - "+.cn.ntp.org.cn"
    - "+.openwrt.pool.ntp.org"
    - "+.time.apple.com"
    - "+.time.windows.com"
    - "+.time.google.com"
    - "+.localdomain.com"
    - "+.airplay.com"
    - "+.apple.com"
    - "+.icloud.com"
    - "+.itunes.apple.com"
    - "+.mzstatic.com"
    - "+.me.com"
    - "+.appstore.com"
    - "+.baidu.com"
    - "+.bdstatic.com"
    - "+.push.apple.com"
    - "+.api.apple-cloudkit.com"
    - "+.apple-mapkit.com"
    - "+.edgesuite.net"
    - "+.akadns.net"
    - "17.0.0.0/8"  # â† å¿…åŠ ï¼šApple çš„æ‰€æœ‰æœåŠ¡ IP
            
  default-nameserver:
    - 202.99.104.68
    - 223.5.5.5
    - 223.6.6.6
    
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query
    - https://223.5.5.5/dns-query
    - https://223.6.6.6/dns-query
 
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://223.5.5.5/dns-query
    - https://223.6.6.6/dns-query
  
  nameserver-policy:
    services.googleapis.cn,googleapis.cn,xn--ngstr-lra8j.com:
      - https://dns.google/dns-query
      - https://dns.cloudflare.com/dns-query
      
    geosite:private,cn:
      - https://dns.alidns.com/dns-query
      - https://223.5.5.5/dns-query
      - https://223.6.6.6/dns-query
    
    geosite:geolocation-!cn:
      - https://1.1.1.1/dns-query
      - https://8.8.8.8/dns-query


pr: &pr {type: select, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©, ğŸ”¯ é¦™æ¸¯æ•…è½¬, ğŸ”¯ æ—¥æœ¬æ•…è½¬, ğŸ”¯ å°æ¹¾æ•…è½¬, ğŸ”¯ ç‹®åŸæ•…è½¬, ğŸ”¯ ä½å€ç‡æ•…è½¬, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ å°æ¹¾è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ ä¿„å›½è‡ªåŠ¨,â™»ï¸ ä¸€å…ƒè‡ªåŠ¨, ğŸ” ä¸€å…ƒå‡è¡¡,â™»ï¸ è‡ªåŠ¨é€‰æ‹©, â™»ï¸ ä½å€ç‡è‡ªåŠ¨, ğŸ” ä½å€ç‡å‡è¡¡, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹,ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹, ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹, ğŸ‡²ğŸ‡´ æ¾³é—¨èŠ‚ç‚¹, ğŸ‡·ğŸ‡º ä¿„å›½èŠ‚ç‚¹, ğŸ•Šï¸ å†·é—¨èŠ‚ç‚¹, ğŸ“¶ ä½å€ç‡èŠ‚ç‚¹, ğŸŒ å…¨éƒ¨èŠ‚ç‚¹, ğŸŸ¢ ç›´è¿]}

proxy-groups:
- {name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©, type: select, proxies: [â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ğŸ”¯ é¦™æ¸¯æ•…è½¬, ğŸ”¯ æ—¥æœ¬æ•…è½¬, ğŸ”¯ ç‹®åŸæ•…è½¬, ğŸ”¯ å°æ¹¾æ•…è½¬, ğŸ”¯ ä½å€ç‡æ•…è½¬, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ å°æ¹¾è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ ä¿„å›½è‡ªåŠ¨, â™»ï¸ ä¸€å…ƒè‡ªåŠ¨, ğŸ” ä¸€å…ƒå‡è¡¡,â™»ï¸ ä½å€ç‡è‡ªåŠ¨, ğŸ” ä½å€ç‡å‡è¡¡, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹, ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹, ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹,  ğŸ‡²ğŸ‡´ æ¾³é—¨èŠ‚ç‚¹, ğŸ‡·ğŸ‡º ä¿„å›½èŠ‚ç‚¹, ğŸ•Šï¸ å†·é—¨èŠ‚ç‚¹, ğŸ“¶ ä½å€ç‡èŠ‚ç‚¹, ğŸŒ å…¨éƒ¨èŠ‚ç‚¹, ğŸŸ¢ ç›´è¿]}
- {name: ğŸ“¹ YouTube, <<: *pr}
- {name: ğŸ€ Google, <<: *pr}
- {name: ğŸ¤– ChatGPT, <<: *pr}
- {name: ğŸ‘¨ğŸ¿â€ğŸ’» GitHub, <<: *pr}
- {name: ğŸ¬ OneDrive, <<: *pr}
- {name: ğŸªŸ Microsoft, <<: *pr}
- {name: ğŸµ TikTok, <<: *pr}
- {name: ğŸ“² Telegram, <<: *pr}
- {name: ğŸ•Šï¸ Twitter, <<: *pr}
- {name: ğŸ¥ NETFLIX, <<: *pr}
- {name: âœˆï¸ Speedtest, <<: *pr}
- {name: ğŸ’¶ PayPal, <<: *pr}
- {name: ğŸ¦… usa, type: select, proxies: [â™»ï¸ ç¾å›½è‡ªåŠ¨, ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹]}
- {name: ğŸ Apple, <<: *pr}
- {name: ğŸ¯ å…¨çƒç›´è¿, type: select, proxies: [ğŸŸ¢ ç›´è¿, ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
- {name: ğŸŸ æ¼ç½‘ä¹‹é±¼, <<: *pr}
- {name: ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, type: select, include-all: true, filter: "(?=.*(æ¸¯|HK|(?i)Hong|æµé‡|å¥—é¤|å®˜ç½‘|åˆ·æ–°|å¼‚å¸¸|é‡ç½®))^((?!(å°|æ—¥|éŸ©|æ·±|è«|ç¾|æ¾³|ä¸“çº¿|çœ‹è¿™é‡Œ|ç›´è¿)).)*$"}
- {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, type: select, include-all: true, filter: "(?=.*(æ—¥|JP|(?i)Japan))^((?!(æ¸¯|å°|éŸ©|æ–°|è«|ç¾|æ¾³|å°¼|ç›´è¿|å€)).)*$"}
- {name: ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹, type: select, include-all: true, filter: "(?=.*(å°|TW|(?i)Taiwan))^((?!(æ¸¯|æ—¥|éŸ©|æ–°|è«|ç¾|æ¾³|ç›´è¿)).)*$"}
- {name: ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹, type: select, include-all: true, filter: "(?=.*(æ–°|SG|(?i)Singapore))^((?!(æ¸¯|å°|éŸ©|æ—¥|è«|ç¾|æ¾³|æµé‡|å¥—é¤|å®˜ç½‘|åˆ·æ–°|å¼‚å¸¸|é‡ç½®|ç›´è¿)).)*$"}
- {name: ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹, type: select, include-all: true, filter: "(?=.*(ç¾|US|(?i)States|America))^((?!(æ¸¯|å°|æ—¥|éŸ©|è«|æ–°|æ¾³|ä¸“çº¿|ç›´è¿)).)*$"}
- {name: ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹, type: select, include-all: true, filter: "(?i)(éŸ©|kr|korea)(?!(ç›´è¿))"}
- {name: ğŸ‡·ğŸ‡º ä¿„å›½èŠ‚ç‚¹, type: select, include-all: true, filter: "(?i)(ä¿„|è«|ru|russia)(?!(ç›´è¿))"}
- {name: ğŸ‡²ğŸ‡´ æ¾³é—¨èŠ‚ç‚¹, type: select, include-all: true, filter: "(?i)(MO|Macao|æ¾³é—¨|æ¾³é–€)(?!(ç›´è¿))"}
- {name: ğŸ•Šï¸ å†·é—¨èŠ‚ç‚¹, type: select, include-all: true, filter: "(?i)^(?!.*(é¦™æ¸¯|hk|hongkong|hong kong|å°æ¹¾|twn|taiwan|å°åŒ—|é«˜é›„|æ—¥æœ¬|jp|japan|æ–°åŠ å¡|sg|singapore|éŸ©å›½|kr|korea|MO|Macao|æ¾³é—¨|æ¾³é–€|ç¾å›½|us|united states|ä¿„|è«|ru|russia|æµé‡|å¥—é¤|å®˜ç½‘|åˆ·æ–°|å¼‚å¸¸|é‡ç½®|ç›´è¿|ä¸€å…ƒ)).*$"}
- {name: ğŸ”¯ é¦™æ¸¯æ•…è½¬, type: fallback, include-all: true, tolerance: 100, interval: 300, filter: "(?=.*(æ¸¯|HK|(?i)Hong|æµé‡|å¥—é¤|å®˜ç½‘|åˆ·æ–°|å¼‚å¸¸|é‡ç½®))^((?!(å°|æ—¥|éŸ©|æ·±|è«|ç¾|æ¾³|ä¸“çº¿|çœ‹è¿™é‡Œ|ç›´è¿)).)*$"}
- {name: ğŸ”¯ æ—¥æœ¬æ•…è½¬, type: fallback, include-all: true, tolerance: 100, interval: 300, filter: "(?=.*(æ—¥|JP|(?i)Japan))^((?!(æ¸¯|å°|éŸ©|æ–°|è«|ç¾|æ¾³|å°¼|ç›´è¿|å€)).)*$"}
- {name: ğŸ”¯ å°æ¹¾æ•…è½¬, type: fallback, include-all: true, tolerance: 100, interval: 300, filter: "(?=.*(å°|TW|(?i)Taiwan))^((?!(æ¸¯|æ—¥|éŸ©|æ–°|è«|ç¾|æ¾³|ç›´è¿)).)*$"}
- {name: ğŸ”¯ ç‹®åŸæ•…è½¬, type: fallback, include-all: true, tolerance: 100, interval: 300, filter: "(?=.*(æ–°|SG|(?i)Singapore))^((?!(æ¸¯|å°|éŸ©|æ—¥|è«|ç¾|æ¾³|æµé‡|å¥—é¤|å®˜ç½‘|åˆ·æ–°|å¼‚å¸¸|é‡ç½®|ç›´è¿)).)*$"}
- {name: â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 100, interval: 300, filter: "(?=.*(æ¸¯|HK|(?i)Hong|æµé‡|å¥—é¤|å®˜ç½‘|åˆ·æ–°|å¼‚å¸¸|é‡ç½®))^((?!(å°|æ—¥|éŸ©|æ·±|è«|ç¾|æ¾³|ä¸“çº¿|çœ‹è¿™é‡Œ|ç›´è¿)).)*$"}
- {name: â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 100, interval: 300, filter: "(?=.*(æ—¥|JP|(?i)Japan))^((?!(æ¸¯|å°|éŸ©|æ–°|è«|ç¾|æ¾³|å°¼|ç›´è¿|å€)).)*$"}
- {name: â™»ï¸ å°æ¹¾è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 100, interval: 300, filter: "(?=.*(å°|TW|(?i)Taiwan))^((?!(æ¸¯|æ—¥|éŸ©|æ–°|è«|ç¾|æ¾³|ç›´è¿)).)*$"}
- {name: â™»ï¸ ç‹®åŸè‡ªåŠ¨, type: url-test, include-all: true, tolerance: 100, interval: 300, filter: "(?=.*(æ–°|SG|(?i)Singapore))^((?!(æ¸¯|å°|éŸ©|æ—¥|è«|ç¾|æ¾³|æµé‡|å¥—é¤|å®˜ç½‘|åˆ·æ–°|å¼‚å¸¸|é‡ç½®|ç›´è¿)).)*$"}
- {name: â™»ï¸ ç¾å›½è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 100, interval: 300, filter: "(?=.*(ç¾|US|(?i)States|America))^((?!(æ¸¯|å°|æ—¥|éŸ©|è«|æ–°|æ¾³|ä¸“çº¿|ç›´è¿)).)*$"}
- {name: â™»ï¸ ä¿„å›½è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 100, interval: 300, filter: "(?=.*(ä¿„|è«|RU|MOS|(?i)Russia))^((?!(æ¸¯|å°|æ—¥|éŸ©|æ–°|ç¾|æ¾³|ç›´è¿)).)*$"}
- {name: â™»ï¸ ä¸€å…ƒè‡ªåŠ¨, type: url-test, include-all: true, tolerance: 30, interval: 180, filter: "(?i)(ä¸“çº¿|çœ‹è¿™é‡Œ)(?!(ç›´è¿|å€))"}
- {name: ğŸ” ä¸€å…ƒå‡è¡¡, type: load-balance, strategy: round-robin, include-all: true, tolerance: 30, interval: 180, filter: "(?i)(ä¸“çº¿|çœ‹è¿™é‡Œ)(?!(ç›´è¿|å€))"}
# æ–°å¢ä½å€ç‡ç›¸å…³
- {name: ğŸ“¶ ä½å€ç‡èŠ‚ç‚¹, type: select, include-all: true, filter: "(?i)å€ç‡"}
- {name: â™»ï¸ ä½å€ç‡è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 100, interval: 300, filter: "(?i)0.5å€ç‡"}
- {name: ğŸ”¯ ä½å€ç‡æ•…è½¬, type: fallback, include-all: true, tolerance: 100, interval: 300, filter: "(?i)0.5å€ç‡"}
- {name: ğŸ” ä½å€ç‡å‡è¡¡, type: load-balance, strategy: round-robin, include-all: true, tolerance: 100, interval: 300, filter: "(?i)0.5å€ç‡"}
- {name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©, type: url-test, include-all: true, tolerance: 100, interval: 300, filter: "^((?!(ğŸŸ¢ ç›´è¿|25å€)).)*$"}
- {name: ğŸŒ å…¨éƒ¨èŠ‚ç‚¹, type: select, include-all: true}




rules:
  # é™¤ä¸­å›½å¤–çš„ QUIC Domain
  # é™¤ä¸­å›½å¤–çš„ QUIC IP
  - AND,((AND,((NETWORK,UDP),(DST-PORT,443))),(NOT,((OR,((GEOSITE,CN),(GEOIP,CN)))))),REJECT
  - RULE-SET,private_domain,ğŸŸ¢ ç›´è¿
  - RULE-SET,direct,ğŸŸ¢ ç›´è¿
  - RULE-SET,apple_domain,ğŸ Apple
  - RULE-SET,proxylite,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,usa_domain,ğŸ¦… usa
  - RULE-SET,ai,ğŸ¤– ChatGPT
  - RULE-SET,github_domain,ğŸ‘¨ğŸ¿â€ğŸ’» GitHub
  - RULE-SET,youtube_domain,ğŸ“¹ YouTube
  - RULE-SET,google_domain,ğŸ€ Google
  - RULE-SET,onedrive_domain,ğŸ¬ OneDrive
  - RULE-SET,microsoft_domain,ğŸªŸ Microsoft
  - RULE-SET,tiktok_domain,ğŸµ TikTok
  - RULE-SET,Twitter,ğŸ•Šï¸ Twitter
  - RULE-SET,speedtest_domain,âœˆï¸ Speedtest
  - RULE-SET,telegram_domain,ğŸ“² Telegram
  - RULE-SET,netflix_domain,ğŸ¥ NETFLIX
  - RULE-SET,paypal_domain,ğŸ’¶ PayPal
  - RULE-SET,gfw_domain,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,geolocation-!cn,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,cn_domain,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,google_ip,ğŸ€ Google,no-resolve
  - RULE-SET,netflix_ip,ğŸ¥ NETFLIX,no-resolve
  - RULE-SET,telegram_ip,ğŸ“² Telegram,no-resolve
  - RULE-SET,cn_ip,ğŸ¯ å…¨çƒç›´è¿
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  class: &class {type: http, interval: 86400, behavior: classical, format: text}
rule-providers: 
  private_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs" }
  direct: { <<: *class, url: "https://raw.githubusercontent.com/Joey7802/Joey7802-openclash/refs/heads/main/Direct.list" }
  proxylite: { <<: *class, url: "https://raw.githubusercontent.com/Joey7802/Joey7802-openclash/refs/heads/main/ProxyLite.list" }
  ai: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-ai-!cn.mrs" }
  youtube_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs" }
  google_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs" }
  github_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs" }
  telegram_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs" }
  netflix_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs" }
  Twitter: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/twitter.mrs" }
  paypal_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs" }
  onedrive_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/onedrive.mrs" }
  microsoft_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs" }
  apple_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple.mrs" }
  speedtest_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ookla-speedtest.mrs" }
  tiktok_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs" }
  usa_domain: { <<: *class, url: "https://raw.githubusercontent.com/Joey7802/Joey7802-openclash/refs/heads/main/USAlist.list" }
  gfw_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/gfw.mrs" }
  geolocation-!cn: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs" }
  cn_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs" }
  cn_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs" }
  google_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs" }
  telegram_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs" }
  netflix_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs" }